server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

  requestLog:
    timeZone: UTC
    appenders:
      - type: console

logging:
  level: INFO
  appenders:
    - type: console
